type Query {
  hello(name: String): String!
  goodbye: String!
  person(id: Int!): Person
  people: [Person!]!
}

type Mutation {
  createPerson(name: String!, email: String): Person!
  updatePerson(id: Int!, name: String, email: String): Person
}

type Person {
  id: Int!
  name: String!
  email: String
}
