type Query {
  hello(name: String): String!

  user(id: Int!): User
  users: [User!]!

  post(id: Int!): Post
  posts: [Post!]!
}

type Mutation {
  createUser(username: String!, avatarUrl: String): User!
  updateUser(id: Int!, username: String, avatarUrl: String): User
  deleteUser(id: Int!): User

  createPost(imageUrls: [String!]!, caption: String!): Post!
  updatePost(id: Int!, imageUrls: [String!], caption: String): Post

}


"""
The number of milliseconds since the [Unix Epoch](https://en.wikipedia.org/wiki/Unix_time)
"""
scalar Posix


type User {
  id: Int!
  username: String!
  avatarUrl: String
  # posts: [Post!]!
}

type Post {
  id: Int!
  imageUrls: [String!]!
  caption: String!
  createdAt: Posix!
  # author: User
}
