type Query {
  hello(name: String): String!
  user(id: Int!): User
  users: [User!]!
}

type Mutation {
  createUser(username: String!, avatarUrl: String): User!
  updateUser(id: Int!, username: String, avatarUrl: String): User
  deleteUser(id: Int!): User

  # createPost(authorId: Int!, imageUrls: [String!]!, caption: String!): Post!
}

type User {
  id: Int!
  username: String!
  avatarUrl: String
  # posts: [Post!]!
}

# type Post {
#   id: Int!
#   imageUrls: [String!]!
#   caption: String!
#   createdAt: Int!
#   author: User
# }
